services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongodb-data-8:/data/db
  hydro:
    build: 
      context: .
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - mongo
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - testdata:/data/file
    command: go-judge

volumes:
  mongodb-data-8:
  node_modules:
  testdata:
